fix(res): Change string categories to int array
rees46/ios-sdk pull request #102
Opened 2024-08-06 13:07 UTC by DanielGreenEngineer

* https://github.com/rees46/planning/issues/120

2024-08-06 13:07 UTC, DanielGreenEngineer commented
Пруф работы поиска без квери:
<img width="1236" alt="Screenshot 2024-08-06 at 3 02 13 PM" src="https://github.com/user-attachments/assets/3b422047-fa71-4c89-b63e-85d41046fab8">

2024-08-06 16:26 UTC, TorinAsakura requested changes
1. Это пруф того, что у тебя запустилось СДК, однако я не вижу пруфа, чтобы у тебя запустилось приложение с данными изменениями
2. Не выделяй пожалуйста логи - читабельность падает на порядок

2024-08-07 10:54 UTC, DanielGreenEngineer commented
> 1. Это пруф того, что у тебя запустилось СДК, однако я не вижу пруфа, чтобы у тебя запустилось приложение с данными изменениями
> 2. Не выделяй пожалуйста логи - читабельность падает на порядок

- Приложение запустилось, иначе бы и запрос не сработал, не вижу смысла вешать скрин эмулятора, так как UI-ая поиска еще нет в сдк, но респонс есть
- Договорились, логи больше не буду выделять

<img width="1163" alt="image" src="https://github.com/user-attachments/assets/6da30a7c-0197-4bfa-8590-4c660a5d3664">

2024-08-07 13:35 UTC, TorinAsakura approved these changes

2024-08-07 13:35 UTC, merged