Feat/reset user data
rees46/ios-sdk pull request #118
Opened 2024-12-05 12:25 UTC by DanielGreenEngineer

2024-12-05 12:29 UTC, DanielGreenEngineer commented
Пруфы 

<img width="1248" alt="Screenshot 2024-12-05 at 12 40 41 PM" src="https://github.com/user-attachments/assets/32a0c300-5acf-4ef4-8091-c26dbb9404af">
<img width="1264" alt="Screenshot 2024-12-05 at 12 39 47 PM" src="https://github.com/user-attachments/assets/c465e85f-2ece-4a89-8622-bd0339676f0e">

2024-12-05 18:33 UTC, TorinAsakura requested changes

2024-12-05 18:33 UTC, TorinAsakura commented on REES46/Classes/Sdk/Extensions/Popup.extension.swift
> +            let subTitleRegex = "<p class=\"popup-\\d+__intro\"[^>]*>(.*?)<\\/p>"
это вот вынеси в отдельный слой регулярок

2024-12-05 18:33 UTC, TorinAsakura commented on REES46/Classes/Sdk/impl/SimplePersonalizationSDK.swift
ты симпл когда уже выкинешь?

2024-12-06 11:31 UTC, DanielGreenEngineer commented on REES46/Classes/Sdk/Extensions/Popup.extension.swift
> +            let subTitleRegex = "<p class=\"popup-\\d+__intro\"[^>]*>(.*?)<\\/p>"
Вынес в отдельный слой.

2024-12-06 11:32 UTC, DanielGreenEngineer commented on REES46/Classes/Sdk/impl/SimplePersonalizationSDK.swift
Надо с критами пока разобраться, а следом заведу задачу на это, но сделаю в любом случае, а то это спагетти читать сложно.

2024-12-06 19:10 UTC, TorinAsakura approved these changes

2024-12-06 19:10 UTC, merged