Feat/push tracking state
rees46/ios-sdk pull request #121
Opened 2024-12-19 15:49 UTC by DanielGreenEngineer

- https://github.com/rees46/development/issues/2114

2024-12-20 14:02 UTC, TorinAsakura requested changes

2024-12-20 14:02 UTC, TorinAsakura commented on REES46/Classes/Notifications/NotificationService.swift
сервис снова раздут

2024-12-20 14:38 UTC, DanielGreenEngineer commented on REES46/Classes/Notifications/NotificationService.swift
Завел отдельную задачу чтобы не Гюрхан не ждал таску. 
Заниматься ею буду после отпуска.
[Задача](https://github.com/rees46/development/issues/2262)

2024-12-23 10:06 UTC, TorinAsakura approved these changes

2024-12-23 10:06 UTC, merged