fix: fixed text block object model and configuring view
rees46/ios-sdk pull request #67
Opened 2024-05-22 11:59 UTC by maksmart96

moved color and opacity configuration from model,
changed position of text block objects to be equal to recieved data from server, changed font configuration from UIFontDescriptor to using UIFont(), fixed text block's label alignment

2024-05-22 16:59 UTC, TorinAsakura requested changes

2024-05-22 16:59 UTC, TorinAsakura commented on REES46/Classes/Stories/TextBlockView/TextBlockView.swift
Где BDD? Нужно тестировать поведение компонента, особенно учитывая множество вариантов шрифта, цвета и выравнивания

2024-05-22 16:59 UTC, TorinAsakura commented on REES46/Classes/Stories/TextBlockView/TextBlockView.swift
> +        if textBlockObject.textBold == true && textBlockObject.textItalic == true {
Отсутствует валидация входных данных из textBlockObject. Например, если fontType не найден в fontMap, то fontName будет пустым.

2024-05-22 16:59 UTC, TorinAsakura commented on REES46/Classes/Stories/TextBlockView/TextBlockView.swift
> +        var fontName = fontMap[fontType] ?? ""
Конкатенация строки шрифта может привести к ошибкам, если fontName пустой. Лучше использовать отдельные параметры для создания UIFont.

2024-05-22 16:59 UTC, TorinAsakura commented on REES46/Classes/Stories/TextBlockView/TextBlockView.swift
Вместо переопределения init(frame:), можно использовать layoutSubviews для настроек лейаута

2024-05-23 09:46 UTC, TorinAsakura requested changes
всё ещё мешанина из ответственности и проблема божественных объектов не решена

2024-05-24 10:27 UTC, TorinAsakura approved these changes

2024-05-24 10:28 UTC, TorinAsakura commented
@maksmart96 долго ждать пока ты билд починишь?

2024-05-24 11:56 UTC, maksmart96 commented
> @maksmart96 долго ждать пока ты билд починишь?

В субботу с утра разберусь и починю ПРы, если не разберусь в субботу то в воскресенье. До начала рабочей недели будет.

2024-05-28 12:32 UTC, merged