Fix/stories text blocks
rees46/ios-sdk pull request #77
Opened 2024-06-17 18:00 UTC by DanielGreenEngineer

https://github.com/rees46/planning/issues/858

2024-06-18 16:25 UTC, TorinAsakura requested changes

2024-06-18 16:25 UTC, TorinAsakura commented on .github/workflows/checks.yaml
> +name: CI
это потом в реюзейблы

2024-06-18 16:25 UTC, TorinAsakura commented on .gitignore
> +GoogleService-Info.plist
последняя строка

2024-06-18 16:25 UTC, TorinAsakura commented on .gitignore
> +GoogleService-Info.plist
последние строки

2024-06-18 16:25 UTC, TorinAsakura commented on DemoApp/Tests/Tests.swift
>      func test_is_device_id_haved_second_run() {
тесты разбиваем по модулям, например:
- service/stories/stories.service.swift
- service/stories/tests/stories.serivce.test.swift

2024-06-18 16:25 UTC, TorinAsakura commented on REES46/Classes/Stories/StoryViewController/CollectionViewCell/StoryCollectionViewCell.swift
> +        // Set the background color
по ходу дела изучи бестпрактиксы и реши вопрос т.н. вью-контроллера - это довольно неудобный паттерн, нужно многое держать в голове, так как он многое позволяет и обо многом нужно думать

Сейчас этот вьюконтроллер стремится к антипаттерну MVC - Massive View Controller

Поставь потом задачу на декомпозицию. Когда у тебя коллекшн вью на 1к+ строк - уже пора задуматься о происходящем

2024-06-18 19:14 UTC, DanielGreenEngineer commented on DemoApp/Tests/Tests.swift
>      func test_is_device_id_haved_second_run() {
Принято

2024-06-18 19:15 UTC, DanielGreenEngineer commented on REES46/Classes/Stories/StoryViewController/CollectionViewCell/StoryCollectionViewCell.swift
> +        // Set the background color
Да, у меня тоже манжраж вызвал это кол-во строк, обязательно задачу заведу и отрефакторю, сначала хочу экшены починить

2024-06-18 19:16 UTC, DanielGreenEngineer commented on REES46/Classes/Stories/StoryViewController/CollectionViewCell/StoryCollectionViewCell.swift
> +        // Set the background color
> по ходу дела изучи бестпрактиксы и реши вопрос т.н. вью-контроллера - это довольно неудобный паттерн, нужно многое держать в голове, так как он многое позволяет и обо многом нужно думать
> 
> Сейчас этот вьюконтроллер стремится к антипаттерну MVC - Massive View Controller
> 
> Поставь потом задачу на декомпозицию. Когда у тебя коллекшн вью на 1к+ строк - уже пора задуматься о происходящем

Да, у меня тоже манжраж вызвал это кол-во строк, обязательно задачу заведу и отрефакторю, сначала хочу экшены починить

2024-06-19 22:56 UTC, DanielGreenEngineer commented on .github/workflows/checks.yaml
> +name: CI
> это потом в реюзейблы

Не совсем понял, что ты имеешь в виду? 
Этот конфиг и так сейчас реюзабл или я путаю?

2024-06-19 22:56 UTC, DanielGreenEngineer commented on .gitignore
> +GoogleService-Info.plist
Добавил

2024-06-19 22:56 UTC, DanielGreenEngineer commented on .gitignore
> +GoogleService-Info.plist
Добавил

2024-06-19 23:02 UTC, DanielGreenEngineer commented
@TorinAsakura 
Текстовые блоки починил, тесты починил, билд починил. 
Задачу на декомпозицию вью контроллера завёл. 
Так же в дальнейшем буду модифицировать конфиг экшена, чтобы кодировать файл .plist или удалять его из репы после успешной проверки, но в данный момент без него не обойтись и не хочу задерживать таску. 
И к слову - спасибо, что перевёл кучу IOS-а на меня!

2024-06-20 10:03 UTC, TorinAsakura approved these changes

2024-06-20 10:03 UTC, TorinAsakura commented
Сверься также с докой на предмет ошибок. Хорошая работа.

2024-06-20 10:03 UTC, merged