fix: Add supporting firebase tokens depends from params
rees46/ios-sdk pull request #79
Opened 2024-06-20 15:05 UTC by DanielGreenEngineer

Поддержка токенов Firebase в iOS SDK 
* [https://github.com/rees46/planning/issues/428](https://github.com/rees46/ios-sdk/pull/url)

2024-06-25 20:59 UTC, TorinAsakura requested changes

2024-06-25 20:59 UTC, TorinAsakura commented on REES46/Classes/SimplePersonalizationSDK.swift
> +                        //                        }
не отправляй закомменченный код в продакшен - дурная привычка будет

2024-06-26 08:15 UTC, DanielGreenEngineer commented on REES46/Classes/SimplePersonalizationSDK.swift
> +                        //                        }
Не имею такой привычки, сам не терплю закоменченого кода, просто забыл спросить как поступить с ним. В предь, весь закоменченный код буду отправлять в урну

2024-06-26 12:53 UTC, DanielGreenEngineer commented on REES46/Classes/SimplePersonalizationSDK.swift
> +                        //                        }
Выкинул закоменченый код. 
Так же хочеться руки оторвать тому, кто хардкодом тут промышлял!
Буду помалу выносить всё кашу в константы

2024-06-26 18:21 UTC, TorinAsakura approved these changes

2024-06-26 18:22 UTC, merged

2024-06-26 18:22 UTC, TorinAsakura commented
refactor: Delete unused code -> chore: ridoff uselless code