Refactor/Separate test file
rees46/ios-sdk pull request #80
Opened 2024-06-21 11:25 UTC by DanielGreenEngineer

Декомпозиция StoryCollectionViewCell и тесты разбиваем по модулям #883
* https://github.com/rees46/planning/issues/883

2024-06-22 07:53 UTC, TorinAsakura requested changes

2024-06-22 07:53 UTC, TorinAsakura commented on DemoApp/service/stories/tests/DeviceIdTests/DeviceIdSaveTests.swift
пример того как мы делаем тесты - паттерн должен быть примерно таким же https://github.com/rees46/workers/tree/master/workers/download-picture-processor/module/src/image

2024-06-22 13:46 UTC, DanielGreenEngineer commented on DemoApp/service/stories/tests/DeviceIdTests/DeviceIdSaveTests.swift
Спасибо, изучу

2024-06-25 10:36 UTC, DanielGreenEngineer commented
@TorinAsakura Привет. Посмотри пожалуйста опытным взглядом на декомпозицию контроллера. Я хочу сегодня добить его, а то у меня скоро крыша поедет от него.

2024-06-27 13:45 UTC, closed without merging