Feat/connection aware loader
rees46/ios-sdk pull request #81
Opened 2024-06-21 15:51 UTC by DanielGreenEngineer

2024-06-27 19:20 UTC, TorinAsakura requested changes

2024-06-27 19:20 UTC, TorinAsakura commented on REES46/Classes/Stories/ConnectionAwareLoader/Use Cases/ImageLoading.swift
пробел в имени папки?

2024-06-27 19:20 UTC, TorinAsakura commented on REES46/Classes/Stories/ConnectionAwareLoader/Presenters/SlidePresenter.swift
> +public class SlidePresenter {
почему тут презентер, а ниже вью? ничего не понимаю

2024-06-27 19:20 UTC, TorinAsakura commented on REES46/Classes/Stories/ConnectionAwareLoader/Data/ImageLoader.swift
> +                    let error = NSError(domain: "com.rees46", code: 1, userInfo: [NSLocalizedDescriptionKey: "Failed to retrieve data."])
не вижу обработки статуса ответов (4хх, 5хх)
ошибки нужно вынести в отдельный слой (читай паттерны errors, exception)

2024-06-28 10:28 UTC, DanielGreenEngineer commented on REES46/Classes/Stories/ConnectionAwareLoader/Use Cases/ImageLoading.swift
Исправил

2024-06-28 10:29 UTC, DanielGreenEngineer commented on REES46/Classes/Stories/ConnectionAwareLoader/Presenters/SlidePresenter.swift
> +public class SlidePresenter {
> почему тут презентер, а ниже вью? ничего не понимаю

Разбил всё по разным директориям

2024-06-28 10:30 UTC, DanielGreenEngineer commented on REES46/Classes/Stories/ConnectionAwareLoader/Data/ImageLoader.swift
> +                    let error = NSError(domain: "com.rees46", code: 1, userInfo: [NSLocalizedDescriptionKey: "Failed to retrieve data."])
Добавил обработку , выкинул упоминание "rees", а так же добавил локализацию

2024-06-28 10:38 UTC, TorinAsakura requested changes

2024-06-28 10:38 UTC, TorinAsakura commented on REES46/Classes/Stories/ConnectionAwareLoader/Presenters/SlidePresenter.swift
> +public class SlidePresenter {
> > почему тут презентер, а ниже вью? ничего не понимаю
> 
> Разбил всё по разным директориям

да я про то, что это разные эксплуатации разных паттернов и я не понимаю зачем нам тут сразу и MVC и MVP?

2024-06-28 11:15 UTC, TorinAsakura approved these changes

2024-06-28 11:21 UTC, merged