Feat: Add unsubscribe functionality
rees46/ios-sdk pull request #83
Opened 2024-06-27 15:50 UTC by DanielGreenEngineer

Добавление метода отписки от триггера "Товар снова в наличии"

* https://github.com/rees46/planning/issues/919
* https://github.com/rees46/planning/issues/920

2024-06-27 17:57 UTC, DanielGreenEngineer commented
@TorinAsakura По ходу дела, продолжаю рефактор всего, что вижу, так как классы по 1,5к строк, вызывают кровь из глаз

2024-06-28 20:20 UTC, TorinAsakura requested changes
ты хендлерами обозвал просто жирные куски которые ты вытаскиваешь из монолита? или как?

2024-06-28 20:20 UTC, TorinAsakura commented on REES46/Classes/Handlers/NotificationHandler.swift
Этот хендлер выглядит  перегруженным и непонятно, к какому именно паттерну он относится. Я опишу основные проблемы, а дальше давай уже сам

1. Жирный класс (God Object):
2. NotificationHandler слишком много знает и делает, что противоречит принципу единственной ответственности (SRP).
3; Непонятно, какую конкретную задачу решает этот хендлер. Лучше было бы разделить его на более специализированные хендлеры.
4. Логика создания параметров для запросов дублируется в методах. Это можно вынести в отдельный метод.
5. Нарушение принципа Dependency Inversion (DIP):

P.S: Класс напрямую зависит от конкретной реализации SimplePersonalizationSDK. Лучше было бы использовать абстракции (протоколы).

2024-07-01 13:40 UTC, DanielGreenEngineer commented on REES46/Classes/Handlers/NotificationHandler.swift
> Этот хендлер выглядит перегруженным и непонятно, к какому именно паттерну он относится. Я опишу основные проблемы, а дальше давай уже сам
> 
> 1. Жирный класс (God Object):
> 2. NotificationHandler слишком много знает и делает, что противоречит принципу единственной ответственности (SRP).
>    3; Непонятно, какую конкретную задачу решает этот хендлер. Лучше было бы разделить его на более специализированные хендлеры.
> 3. Логика создания параметров для запросов дублируется в методах. Это можно вынести в отдельный метод.
> 4. Нарушение принципа Dependency Inversion (DIP):
> 
> P.S: Класс напрямую зависит от конкретной реализации SimplePersonalizationSDK. Лучше было бы использовать абстракции (протоколы).

Спасибо за подробное описание! Поресерчил этот момент, вношу корректировки

2024-07-01 19:20 UTC, DanielGreenEngineer commented on REES46/Classes/Handlers/NotificationHandler.swift
@TorinAsakura 

* Использование сервисов с протоколами: Перелопатил все хендлеры, разделив их функциональность на отдельные сервисы, реализующие соответствующие протоколы.
* Применение принципа инверсии зависимостей: Пересмотрел зависимости от конкретной реализации SimplePersonalizationSDK и перешел к использованию протоколов в моих сервисах. Теперь есть гибкость моего кода, соответствуя принципу Dependency Inversion.

Еще раз спасибо за подробный фидбек, я ценю такие наставнические коменты в ревью!

2024-07-01 20:47 UTC, TorinAsakura requested changes
Чисти и мержимся

2024-07-01 20:47 UTC, TorinAsakura commented on ServicesImplementation/PushTokenNotificationServiceImpl.swift
> +//
категорически прошу не мусорить штатными комментами IDE

2024-07-01 22:11 UTC, DanielGreenEngineer commented on ServicesImplementation/PushTokenNotificationServiceImpl.swift
> +//
Коменты почистил, но экшен валиться из-за каких то подписей, не пойму какого хрена оно слетело, я туда не лазил, но сейчас разбираться уже сил нет.

2024-07-02 09:09 UTC, TorinAsakura submitted a review, later dismissed

2024-07-02 09:13 UTC, TorinAsakura commented
@DanielGreenEngineer предоставь пруфы по ПРу, можно скриншот, но, лучше скринкаст

2024-07-02 16:51 UTC, DanielGreenEngineer commented
> @DanielGreenEngineer предоставь пруфы по ПРу, можно скриншот, но, лучше скринкаст

Цепляю скриншот а так же текстом ниже метод и лог.

<img width="1240" alt="Screenshot 2024-07-02 at 6 49 59 PM" src="https://github.com/rees46/ios-sdk/assets/33836630/309eb639-fd50-4f28-b6d7-bf5853d7d549">

**sdk.unsubscribeForBackInStock(
            itemIds: ["784"],
            email: "mail@example.com",
            phone: "+19999999999"
        ) { unsubscribeResponse in
            print("Unsubscribe response received")
            switch unsubscribeResponse {
            case .success():
                print("Successfully unsubscribed from back in stock notifications.")
                print("Response: \(unsubscribeResponse)")
            case let .failure(error):
                print("Unsubscribe failed with error: \(error)")
                switch error {
                case let .custom(customError):
                    print("Error:", customError)
                default:
                    print("Error:", error.localizedDescription)
                }
            }
        }**
        
        Unsubscribe response received
Successfully unsubscribed from back in stock notifications.
Response: success()

2024-07-02 17:52 UTC, TorinAsakura approved these changes

2024-07-02 17:52 UTC, merged