Feat/remove confidential file
rees46/ios-sdk pull request #88
Opened 2024-07-22 10:16 UTC by DanielGreenEngineer

* https://github.com/rees46/planning/issues/960

2024-07-22 17:55 UTC, TorinAsakura requested changes

2024-07-22 17:55 UTC, TorinAsakura commented on .gitignore
>  DemoApp/Pods
можешь использовать вайлдкард чтобы исключать всё, что находится в этой папке

2024-07-22 18:06 UTC, DanielGreenEngineer commented on .gitignore
>  DemoApp/Pods
Добавил

2024-07-22 19:32 UTC, DanielGreenEngineer commented
@TorinAsakura Есть у меня сомнения в тестах. То что я выкинул из них лишнюю инициализацию сдк вроде помогло, а вроде и нет. Глянь опытным глазом, может мы можем вообще сократить до минимума и на данном этапе, проверять создание сдк и не более. Мне кажеться 6 минут все равно это много

2024-07-23 15:01 UTC, TorinAsakura commented
> @TorinAsakura Есть у меня сомнения в тестах. То что я выкинул из них лишнюю инициализацию сдк вроде помогло, а вроде и нет. Глянь опытным глазом, может мы можем вообще сократить до минимума и на данном этапе, проверять создание сдк и не более. Мне кажеться 6 минут все равно это много

причём тут тесты? у тебя задача была потереть конфиденциальные данные

2024-07-23 15:02 UTC, DanielGreenEngineer commented
> > @TorinAsakura Есть у меня сомнения в тестах. То что я выкинул из них лишнюю инициализацию сдк вроде помогло, а вроде и нет. Глянь опытным глазом, может мы можем вообще сократить до минимума и на данном этапе, проверять создание сдк и не более. Мне кажеться 6 минут все равно это много
> 
> причём тут тесты? у тебя задача была потереть конфиденциальные данные

Я решил попутно с тестами разобраться, чтобы не оставлять на "потом"

2024-07-23 15:03 UTC, TorinAsakura commented
> > > @TorinAsakura Есть у меня сомнения в тестах. То что я выкинул из них лишнюю инициализацию сдк вроде помогло, а вроде и нет. Глянь опытным глазом, может мы можем вообще сократить до минимума и на данном этапе, проверять создание сдк и не более. Мне кажеться 6 минут все равно это много
> > 
> > 
> > причём тут тесты? у тебя задача была потереть конфиденциальные данные
> 
> Я решил попутно с тестами разобраться, чтобы не оставлять на "потом"

для тестов отдельная задача должна быть, никаких попутно

вот из-за твоих "попутно" такая простая задача как прикрытие конфиденциальных данных разрослась аж на два дня

2024-07-23 15:06 UTC, DanielGreenEngineer commented
> > > > @TorinAsakura Есть у меня сомнения в тестах. То что я выкинул из них лишнюю инициализацию сдк вроде помогло, а вроде и нет. Глянь опытным глазом, может мы можем вообще сократить до минимума и на данном этапе, проверять создание сдк и не более. Мне кажеться 6 минут все равно это много
> > > 
> > > 
> > > причём тут тесты? у тебя задача была потереть конфиденциальные данные
> > 
> > 
> > Я решил попутно с тестами разобраться, чтобы не оставлять на "потом"
> 
> для тестов отдельная задача должна быть, никаких попутно
> 
> вот из-за твоих "попутно" такая простая задача как прикрытие конфиденциальных данных разрослась аж на два дня

Хорошо, заведу отдельную задачу

2024-07-23 15:16 UTC, TorinAsakura commented on .github/workflows/checks.yaml
> +        run: rm -f GoogleService-Info.plist
последняя строка

2024-07-23 15:16 UTC, TorinAsakura commented on DemoApp/REES46Demo/AppDelegate.swift
откати изменения связанные с тестами

2024-07-23 15:22 UTC, DanielGreenEngineer commented on .github/workflows/checks.yaml
> +        uses: actions/checkout@v2
Нет, поднял до 4 актуальной

2024-07-23 15:22 UTC, DanielGreenEngineer commented on .github/workflows/checks.yaml
> +        run: rm -f GoogleService-Info.plist
Добавил

2024-07-23 15:22 UTC, DanielGreenEngineer commented on DemoApp/REES46Demo/AppDelegate.swift
Вернул

2024-07-24 09:24 UTC, TorinAsakura approved these changes

2024-07-24 09:24 UTC, merged