fix: Fix git actions and optimizing tests
rees46/ios-sdk pull request #92
Opened 2024-07-25 09:44 UTC by DanielGreenEngineer

* https://github.com/rees46/planning/issues/1310

2024-07-28 14:09 UTC, TorinAsakura commented
> и стоит ли

нет, это уже близко к норме

2024-07-28 14:17 UTC, TorinAsakura requested changes

2024-07-28 14:17 UTC, TorinAsakura commented on DemoApp/REES46Demo/AppDelegate.swift
>          print("2. Register push")
Что-то не очень понятен порядок:
0.
А.
2.
втф?

2024-07-28 14:17 UTC, TorinAsakura commented on DemoApp/REES46Demo/AppDelegate.swift
>      private func exampleUsageSdk(){
я тебя просил экземпл убрать из делегейта уже лет сто тому назад

2024-07-29 08:51 UTC, DanielGreenEngineer commented on DemoApp/REES46Demo/AppDelegate.swift
>          print("2. Register push")
Выкинул вовсе эти логи, они бесполезны

2024-07-29 08:51 UTC, DanielGreenEngineer commented on DemoApp/REES46Demo/AppDelegate.swift
>      private func exampleUsageSdk(){
Удалил

2024-07-29 11:18 UTC, TorinAsakura approved these changes

2024-07-29 11:18 UTC, merged