feat: Categories and brands in full search
rees46/ios-sdk pull request #95
Opened 2024-07-26 09:12 UTC by DanielGreenEngineer

* https://github.com/rees46/planning/issues/646

2024-07-29 10:44 UTC, DanielGreenEngineer commented
**Подтверждение работы:**
* Отображение брендов
<img width="1246" alt="image" src="https://github.com/user-attachments/assets/f85e64c1-b050-4da5-b075-f1b39b44f01d">
<img width="1243" alt="image" src="https://github.com/user-attachments/assets/e1939663-bbd5-43d7-9e8a-2bb92bd5fc8e">

* Отображение категорий 
<img width="950" alt="image" src="https://github.com/user-attachments/assets/83e5f504-5400-4cec-8819-2730c6b53f17">

2024-07-29 19:04 UTC, TorinAsakura requested changes

2024-07-29 19:04 UTC, TorinAsakura commented on REES46/Classes/ServicesImplementation/SearchServiceImpl.swift
1. Настройка URLSessionConfiguration и обработка результата запроса повторяются в методах searchBlank и search
2. Метод search слишком длинный и сложный
3. Жёсткая зависимость от PersonalizationSDK
4. Для каких целей ты используешь замыкания для асинхронной обработки?

2024-07-30 15:38 UTC, DanielGreenEngineer commented on REES46/Classes/ServicesImplementation/SearchServiceImpl.swift
> 1. Настройка URLSessionConfiguration и обработка результата запроса повторяются в методах searchBlank и search
> 2. Метод search слишком длинный и сложный
> 3. Жёсткая зависимость от PersonalizationSDK
> 4. Для каких целей ты используешь замыкания для асинхронной обработки?

* Вынес в отдельные методы обработку
* Также разделил метод search, на более мелкие части
* Это мы с тобой обсудили голосом
* Замыкание тут используеться для обработки результата и ошибок

2024-07-30 15:46 UTC, TorinAsakura requested changes

2024-07-30 15:46 UTC, TorinAsakura commented on REES46/Classes/ServicesImplementation/SearchServiceImpl.swift
> * Замыкание тут используеться для обработки результата и ошибок

да, искренне рад, только почему ты не используешь современные асинхронные методы доступные в iOS, а старые допотопные замыкания?

2024-07-30 15:48 UTC, DanielGreenEngineer commented on REES46/Classes/ServicesImplementation/SearchServiceImpl.swift
> > * Замыкание тут используеться для обработки результата и ошибок
> 
> да, искренне рад, только почему ты не используешь современные асинхронные методы доступные в iOS, а старые допотопные замыкания?

Я их еще не изучил, в следующем риквесте с нотификациями применю, там +- аналогичная ситуация

2024-07-30 15:52 UTC, TorinAsakura approved these changes

2024-07-30 15:52 UTC, merged